/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    appointments: Appointment;
    users: User;
    media: Media;
    visitors: Visitor;
    'travel-logs': TravelLog;
    'parcel-logs': ParcelLog;
    'phone-calls': PhoneCall;
    vehicles: Vehicle;
    employees: Employee;
    clients: Client;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    appointments: AppointmentsSelect<false> | AppointmentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    visitors: VisitorsSelect<false> | VisitorsSelect<true>;
    'travel-logs': TravelLogsSelect<false> | TravelLogsSelect<true>;
    'parcel-logs': ParcelLogsSelect<false> | ParcelLogsSelect<true>;
    'phone-calls': PhoneCallsSelect<false> | PhoneCallsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments".
 */
export interface Appointment {
  id: string;
  visitorName: string;
  company: string;
  email: string;
  phone: string;
  purpose: string;
  employeeToMeet: string | Employee;
  /**
   * Fallback if no employee relationship
   */
  employeeToMeetText?: string | null;
  department: 'IT' | 'Sales' | 'Marketing' | 'Legal' | 'Executive' | 'HR' | 'Finance' | 'Operations';
  scheduledTime: string;
  duration: number;
  status?: ('pending' | 'confirmed' | 'scheduled' | 'cancelled' | 'completed' | 'no-show') | null;
  appointmentType?: ('meeting' | 'interview' | 'delivery' | 'maintenance' | 'other') | null;
  notes?: string | null;
  visitorArrived?: boolean | null;
  checkInTime?: string | null;
  checkOutTime?: string | null;
  sendReminder?: boolean | null;
  reminderSent?: boolean | null;
  reminderSentAt?: string | null;
  createdBy?: (string | null) | User;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: string;
  name: string;
  employeeId: string;
  department?: ('it' | 'hr' | 'finance' | 'operations' | 'sales') | null;
  email: string;
  phone?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'reception' | 'security' | 'employee';
  department?: string | null;
  phone?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors".
 */
export interface Visitor {
  id: string;
  name: string;
  email?: string | null;
  phone: string;
  company?: string | null;
  purpose: string;
  employeeToMeet?: (string | null) | Employee;
  employeeToMeetName?: string | null;
  checkInTime?: string | null;
  checkOutTime?: string | null;
  status?: ('checked-in' | 'checked-out' | 'expected') | null;
  notes?: string | null;
  badgeNumber?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-logs".
 */
export interface TravelLog {
  id: string;
  employee: string | Employee;
  destination: string;
  purpose: string;
  departureTime: string;
  expectedReturn?: string | null;
  actualReturn?: string | null;
  status: 'pending' | 'approved' | 'departed' | 'returned' | 'cancelled';
  travelType?: ('business' | 'client_visit' | 'conference' | 'training' | 'other') | null;
  transportation?: ('flight' | 'car' | 'bus' | 'train' | 'other') | null;
  accommodation?: string | null;
  estimatedCost?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcel-logs".
 */
export interface ParcelLog {
  id: string;
  trackingNumber?: string | null;
  deliveryNoteNumber?: string | null;
  serialNumbers?:
    | {
        serialNumber: string;
        id?: string | null;
      }[]
    | null;
  from: string;
  senderType: 'incoming' | 'outgoing' | 'other';
  to: string | Employee;
  description: string;
  receivedAt?: string | null;
  collectedAt?: string | null;
  status?: ('received' | 'collected' | 'returned') | null;
  weight?: string | null;
  dimensions?: string | null;
  deliveryService?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-calls".
 */
export interface PhoneCall {
  id: string;
  employee: string | Employee;
  callerName?: string | null;
  callerNumber: string;
  purpose: string;
  startTime?: string | null;
  endTime?: string | null;
  duration?: number | null;
  cost?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: string;
  registrationNumber: string;
  vehicleType: 'company-car' | 'employee-personal' | 'visitor' | 'delivery';
  ownerName: string;
  ownerPhone?: string | null;
  purpose?: string | null;
  entryTime?: string | null;
  exitTime?: string | null;
  currentMileage?: number | null;
  notes?: string | null;
  securityGuard?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: string;
  companyName: string;
  contactPerson: string;
  email: string;
  phone: string;
  address?: string | null;
  city?: string | null;
  country?: string | null;
  industry?: ('technology' | 'finance' | 'healthcare' | 'retail' | 'manufacturing' | 'other') | null;
  clientSince?: string | null;
  status?: ('active' | 'inactive' | 'prospect') | null;
  notes?: string | null;
  documents?:
    | {
        document?: (string | null) | Media;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  assignedEmployee?: (string | null) | Employee;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'appointments';
        value: string | Appointment;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'visitors';
        value: string | Visitor;
      } | null)
    | ({
        relationTo: 'travel-logs';
        value: string | TravelLog;
      } | null)
    | ({
        relationTo: 'parcel-logs';
        value: string | ParcelLog;
      } | null)
    | ({
        relationTo: 'phone-calls';
        value: string | PhoneCall;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: string | Vehicle;
      } | null)
    | ({
        relationTo: 'employees';
        value: string | Employee;
      } | null)
    | ({
        relationTo: 'clients';
        value: string | Client;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "appointments_select".
 */
export interface AppointmentsSelect<T extends boolean = true> {
  visitorName?: T;
  company?: T;
  email?: T;
  phone?: T;
  purpose?: T;
  employeeToMeet?: T;
  employeeToMeetText?: T;
  department?: T;
  scheduledTime?: T;
  duration?: T;
  status?: T;
  appointmentType?: T;
  notes?: T;
  visitorArrived?: T;
  checkInTime?: T;
  checkOutTime?: T;
  sendReminder?: T;
  reminderSent?: T;
  reminderSentAt?: T;
  createdBy?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  department?: T;
  phone?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "visitors_select".
 */
export interface VisitorsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  purpose?: T;
  employeeToMeet?: T;
  employeeToMeetName?: T;
  checkInTime?: T;
  checkOutTime?: T;
  status?: T;
  notes?: T;
  badgeNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "travel-logs_select".
 */
export interface TravelLogsSelect<T extends boolean = true> {
  employee?: T;
  destination?: T;
  purpose?: T;
  departureTime?: T;
  expectedReturn?: T;
  actualReturn?: T;
  status?: T;
  travelType?: T;
  transportation?: T;
  accommodation?: T;
  estimatedCost?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parcel-logs_select".
 */
export interface ParcelLogsSelect<T extends boolean = true> {
  trackingNumber?: T;
  deliveryNoteNumber?: T;
  serialNumbers?:
    | T
    | {
        serialNumber?: T;
        id?: T;
      };
  from?: T;
  senderType?: T;
  to?: T;
  description?: T;
  receivedAt?: T;
  collectedAt?: T;
  status?: T;
  weight?: T;
  dimensions?: T;
  deliveryService?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "phone-calls_select".
 */
export interface PhoneCallsSelect<T extends boolean = true> {
  employee?: T;
  callerName?: T;
  callerNumber?: T;
  purpose?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  cost?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  registrationNumber?: T;
  vehicleType?: T;
  ownerName?: T;
  ownerPhone?: T;
  purpose?: T;
  entryTime?: T;
  exitTime?: T;
  currentMileage?: T;
  notes?: T;
  securityGuard?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  name?: T;
  employeeId?: T;
  department?: T;
  email?: T;
  phone?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  companyName?: T;
  contactPerson?: T;
  email?: T;
  phone?: T;
  address?: T;
  city?: T;
  country?: T;
  industry?: T;
  clientSince?: T;
  status?: T;
  notes?: T;
  documents?:
    | T
    | {
        document?: T;
        description?: T;
        id?: T;
      };
  assignedEmployee?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}